version: '3.8'

services:
  nl2query-be:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nl2query
    image: 277304117720.dkr.ecr.ap-south-1.amazonaws.com/nl2query-be:dev
    command: "gunicorn -w 2 -b 0.0.0.0:8000 --worker-class gevent --log-level debug project.wsgi:application"
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - nl2query
    
networks:
    nl2query:
      driver: bridge
