version: '3.8'

services:
  ramailo-be:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ramailo
    command: "gunicorn -w 2 -b 0.0.0.0:8000 --worker-class gevent --log-level debug project.wsgi:application"
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - ramailo
    
networks:
    ramailo:
      driver: bridge
